language: cpp
sudo: required
dist: trusty

os:
  - linux

compiler:
  - clang

env:
  global:
    # - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"
    # - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
    # - CMAKE_OPTIONS="-DOPTION_BUILD_EXAMPLES=On"
    - secure: "kuCyatatsoOwecL0xJJJ6fq03z28HzMJrR7BKHCt6kfdvytEOs/UrmpS+uVtoSlTv5b/wqip9k9Zy7RF5EYhQOHeb5bwEjnamNRn5cTnujbFMYyIvwM3qOtcmG0QPdaOKCD0obmxeB+yjiL+SSxZ+0n392Qrj60YUzSIeIOhecaajydjSDV2l0ObJ6MG1+dw47NeSu+jiWVmMeuZhPAlUGRrQq986qbpCNWi/5qoOXHtJCxS97pg4qS5xbhXJ9GuouKvoxBlYeF5Mux3/AtzGHZ1r6Ru1EqMuFsrRLdaPamTDnCThaNihGFTo86Arm2+vXbKF/Kctcj5aH2PwKUV0b1zYao1+WDtKn0eVaUJ9Wn1zE2zoQ/7S781uRp0Hfatf2qqTrZdGSQSWEb5/oAuvm0BCQmloEJzG93iLNKC6la1rB9p1DtjeO9qRiLWyc9nt0zaLhdBFIPfRKEF12u32dqNQnP0mMzufkvvJ8iR8XxQgIR4jqSeMkZNqxKjEb3Pxp9/EkwtIWzvFcMigPkEylTuHTQw1IGMB9Qryn3E6cHjJ8LtazbKAT5aXJllBvPtEdYaIyRP5F7QiC0apr5o/pmZ9jVwq6OleOx7ui7uxTxRteaOCNiIi3MFvyv3Yx/F6NX44Db/BfeHQqy2v7Pyp78eMAMRhGLQl1pGWADbBCQ="
  matrix:
    # - CMAKE_CONFIGURATION=release BUILD_DIR=build
    - CMAKE_CONFIGURATION=debug BUILD_DIR=build-debug

matrix:
  exclude:
  - os: osx
    compiler: gcc

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  # clang
  - sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.8 90
  - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.8 90
  # - sudo apt-get install -y libc++-dev libc++abi-dev
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -qq cmake  libboost-all-dev libsfml-dev  cppcheck clang-tidy-3.8; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install  cppcheck; fi


before_script:
  - ./configure
  - if [ $CMAKE_CONFIGURATION == release ]; then ./configure; fi
  - if [ $CMAKE_CONFIGURATION == debug ]; then ./configure debug; fi

script:
  - if [[ "${COVERITY_SCAN_BRANCH}" == 1 ]];
      then
        echo "Don't build on coverty_scan branch.";
        exit 0;
    fi
  - cmake --build $BUILD_DIR
  - cmake --build $BUILD_DIR --target test
  - cmake --build $BUILD_DIR --target check-all

# safelist
branches:
  only:
    - master
    - coverity_scan
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - clang-3.8
      - g++-6
      - gcc-6
  coverity_scan:
    project:
      name: "drumaddict/cpp-maze"
      description: "Build submitted via Travis CI"
    notification_email: kabasakalis@gmail.com
    build_command_prepend: "cd ."
    build_command:   cmake --build $BUILD_DIR
    branch_pattern: coverity_scan


